### ISSUE TITLE
Working as described but what is the point of the weather setup in settings.h if no weather displayed on any face. 

### ISSUE THREAD

**Issue by Techsteps** [BraininaBowl/Brainwork-for-Watchy#2]
I am sorry this isn't really an "issue" so feel free to close if you want. These are beautiful and I appreciate all the hard work... but, went through to setup all the openweather config in settings.h and none of the faces actually utilize weather, correct? Unless I am missing something?

**Comment by BraininaBowl** [comment]
The current version doesn't use weather display (previous versions did), but Watchy needs the settings for NTP sync. If you don't use NTP sync, you can leave those blank.
